"""Bubbles — topic groupings that own a Markdown report.

A bubble has a slug (filesystem key) and a display name. Bubbles are tracked in a registry
(``bubbles.yaml``) so they can carry approval state + report instructions and exist
*standalone* (no PDFs yet). A bubble is also surfaced if any PDF carries its slug, so tags
applied directly to a PDF still produce a bubble.

Report generation is gated: a bubble must be ``approved`` before a report can be generated.
Auto-suggested bubbles (from the tagger) start ``approved=False`` and wait in the UI.

All paths resolve against the active per-user context root.
"""
from __future__ import annotations

import json as _json
import os
import re
import secrets
from datetime import datetime, timezone
from pathlib import Path

import yaml
from slugify import slugify

from . import assets, paths


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def _atomic_write(path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(text)
    os.replace(tmp, path)


# --------------------------------------------------------------------------- #
# Registry
# --------------------------------------------------------------------------- #
def load_registry() -> dict:
    path = paths.BUBBLES_YAML
    if not path.exists():
        return {}
    return (yaml.safe_load(path.read_text()) or {}).get("bubbles", {})


def save_registry(reg: dict) -> None:
    _atomic_write(paths.BUBBLES_YAML, yaml.safe_dump({"bubbles": reg}, sort_keys=True,
                                                     allow_unicode=True))


def touch_bubble(slug: str, *, when: "str | None" = None) -> None:
    """Update a bubble's last-edited timestamp, materializing PDF-derived bubbles if needed."""
    reg = load_registry()
    entry = reg.get(slug)
    if entry is None:
        entry = {"name": slug_to_name(slug), "approved": False, "instructions": "",
                 "created_at": _now_iso()}
    entry["last_edited_at"] = when or _now_iso()
    reg[slug] = entry
    save_registry(reg)


def write_citation_file(slug: str, asset_metas: "list[dict] | None" = None) -> None:
    """Write this bubble's generated paper inventory for scientist sessions.

    The implementation name is retained for compatibility, but the generated artifact is an
    asset inventory. BibTeX is optional metadata, not the criterion for whether a paper belongs
    in a scientist session.
    """
    title = slug_to_name(slug)
    lines = [
        f"# Attached Papers & Citation BibTeX for {title}",
        "",
        "This file is generated by lockedin for scientist sessions.",
        "Every asset attached to this bubble is listed below, ordered by relevance.",
        "Use a BibTeX key with \\cite{key} only when that asset provides one.",
        "Do not edit this file; edit asset BibTeX from the lockedin web UI.",
        "",
    ]
    attached = []
    for meta in asset_metas if asset_metas is not None else assets.list_assets():
        if slug not in (meta.get("idea_bubbles") or []):
            continue
        score = assets.bubble_scores(meta).get(slug, 5)
        attached.append((int(score), meta))
    attached.sort(key=lambda item: (-item[0], (item[1].get("title") or item[1].get("filename") or "").lower()))
    for score, meta in attached:
        bibtex = str(meta.get("bibliography") or "").strip()
        pdf_id = meta.get("pdf_id") or "unknown-asset"
        asset_title = meta.get("title") or meta.get("filename") or pdf_id
        lines.extend([f"## [Relevance {score}] {asset_title}", "", f"- Asset id: `{pdf_id}`"])
        if meta.get("url_source"):
            lines.append(f"- Source URL: {meta['url_source']}")
        if bibtex:
            lines.extend(["", "```bibtex", *bibtex.splitlines(), "```"])
        else:
            lines.append("- No BibTeX is saved for this asset yet; do not invent a citation key.")
        lines.append("")
    if not attached:
        lines.append("_No assets are attached to this bubble._")
        lines.append("")
    path = paths.bubble_dir(slug) / "_lockedin_papers.md"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines))
    legacy = paths.bubble_dir(slug) / "_lockedin_citations.md"
    if legacy.exists():
        legacy.unlink()


def refresh_citation_files(slugs: "set[str] | list[str] | None" = None) -> None:
    """Refresh generated citation inventory files for selected or all approved bubbles."""
    asset_metas = assets.list_assets()
    if slugs is None:
        targets = [b["slug"] for b in all_bubbles() if b.get("approved")]
    else:
        targets = sorted({s for s in slugs if s})
    for slug in targets:
        write_citation_file(slug, asset_metas)


def propose_bubble(name: str) -> str:
    """Register an auto-suggested bubble (approved=False). Idempotent; never downgrades approval."""
    slug = slugify(name)
    if not slug:
        return slug
    reg = load_registry()
    if slug not in reg:
        now = _now_iso()
        reg[slug] = {"name": name.strip(), "approved": False, "instructions": "",
                     "created_at": now, "last_edited_at": now}
        save_registry(reg)
    return slug


def create_bubble(name: str) -> str:
    """User-created standalone bubble (approved=True).

    If the slug already exists, keep its existing entry untouched except to ensure it's approved —
    do NOT overwrite the display ``name`` (a rename) or share state. The ``name`` here is only the
    seed for a *new* bubble; for an existing one, identity is the slug and the name is display-only.
    """
    slug = slugify(name)
    if not slug:
        raise ValueError("Bubble name must contain letters or numbers.")
    reg = load_registry()
    entry = reg.get(slug)
    if entry is None:
        now = _now_iso()
        reg[slug] = {"name": name.strip(), "approved": True, "instructions": "",
                     "created_at": now, "last_edited_at": now}
    else:
        entry["approved"] = True
        entry["last_edited_at"] = _now_iso()
    save_registry(reg)
    return slug


def approve_bubble(slug: str, instructions: str = "") -> dict:
    reg = load_registry()
    entry = reg.get(slug)
    if entry is None:
        # bubble exists only via PDF tags — materialize it in the registry
        now = _now_iso()
        entry = {"name": slug_to_name(slug), "approved": True, "instructions": instructions,
                 "created_at": now, "last_edited_at": now}
    else:
        entry["approved"] = True
        if instructions:
            entry["instructions"] = instructions
        entry["last_edited_at"] = _now_iso()
    reg[slug] = entry
    save_registry(reg)
    return entry


def rename_bubble(slug: str, new_name: str) -> dict:
    """Update the display name of a bubble (slug stays the same)."""
    new_name = new_name.strip()
    if not new_name:
        raise ValueError("Bubble name cannot be empty.")
    reg = load_registry()
    if slug not in reg:
        raise KeyError(f"Bubble {slug!r} not found.")
    reg[slug]["name"] = new_name
    reg[slug]["last_edited_at"] = _now_iso()
    save_registry(reg)
    return reg[slug]


def delete_bubble(slug: str) -> None:
    """Remove a bubble from the registry, delete its reports, and strip its tag from all PDFs."""
    import shutil

    # Remove from registry
    reg = load_registry()
    reg.pop(slug, None)
    save_registry(reg)

    # Delete the reports directory (pages + assets)
    bdir = paths.bubble_dir(slug)
    if bdir.exists():
        shutil.rmtree(bdir)

    # Strip the slug from every PDF's idea_bubbles + tags
    for m in assets.list_assets():
        if slug in m.get("idea_bubbles", []):
            idx = m["idea_bubbles"].index(slug)
            m["idea_bubbles"].remove(slug)
            # also remove the corresponding display tag (same index if lists are in sync)
            if idx < len(m.get("tags", [])):
                m["tags"].pop(idx)
            else:
                # fall back: remove any tag whose slug matches
                m["tags"] = [t for t in m.get("tags", []) if slugify(t) != slug]
            scores = dict(m.get("bubble_scores") or {})
            scores.pop(slug, None)
            m["bubble_scores"] = {s: scores[s] for s in m.get("idea_bubbles", []) if s in scores}
            assets.save_meta(m["pdf_id"], m)


def is_approved(slug: str) -> bool:
    return bool(load_registry().get(slug, {}).get("approved"))


def get_instructions(slug: str) -> str:
    return load_registry().get(slug, {}).get("instructions", "")


# --------------------------------------------------------------------------- #
# Derivation / listing
# --------------------------------------------------------------------------- #
def _pdf_slug_names(asset_metas: list[dict] | None = None) -> dict[str, str]:
    """Map slug -> a display name, derived from PDF tags.

    Callers that are already building a bubble view pass their one asset-metadata scan here.
    This avoids repeatedly parsing every ``meta.yaml`` for each bubble in the same response.
    """
    out: dict[str, str] = {}
    for m in asset_metas if asset_metas is not None else assets.list_assets():
        tags = m.get("tags", [])
        bubbles = m.get("idea_bubbles", [])
        for i, slug in enumerate(bubbles):
            if slug and slug not in out:
                out[slug] = tags[i] if i < len(tags) else slug
    return out


def slug_to_name(slug: str, *, reg: dict | None = None,
                 pdf_names: dict[str, str] | None = None) -> str:
    reg = load_registry() if reg is None else reg
    if slug in reg and reg[slug].get("name"):
        return reg[slug]["name"]
    return (pdf_names if pdf_names is not None else _pdf_slug_names()).get(slug, slug)


def tag_for_slug(slug: str, *, reg: dict | None = None,
                 pdf_names: dict[str, str] | None = None) -> str:
    """A display tag string guaranteed to slugify back to ``slug`` (the bubble's membership key).

    A bubble's display ``name`` is cosmetic and may be renamed freely, but membership is keyed by
    the immutable slug (``idea_bubbles`` = slugified tags). So when we tag a PDF into a bubble we
    must use a tag that *slugifies to the slug* — never the (possibly-renamed) display name, which
    would slugify to a different, phantom slug and split the bubble's papers. Prefer an existing
    member's tag (keeps a bubble's tag display consistent), then the registry name if it still maps
    to this slug, else a readable de-slugified form of the slug.
    """
    existing = (pdf_names if pdf_names is not None else _pdf_slug_names()).get(slug)
    if existing and assets.slug_of(existing) == slug:
        return existing
    name = ((load_registry() if reg is None else reg).get(slug) or {}).get("name", "")
    if name and assets.slug_of(name) == slug:
        return name
    readable = slug.replace("-", " ")
    return readable if assets.slug_of(readable) == slug else slug


def _with_bubble_score(meta: dict, slug: str) -> dict:
    out = dict(meta)
    scores = assets.bubble_scores(out)
    out["bubble_scores"] = scores
    out["bubble_score"] = scores.get(slug, 5)
    return out


def _paper_sort_key(meta: dict) -> tuple[int, str, str]:
    title = (meta.get("title") or meta.get("filename") or "").lower()
    return (-int(meta.get("bubble_score", 5)), title, meta.get("pdf_id", ""))


def pdfs_for_bubble(slug: str, *, asset_metas: list[dict] | None = None) -> list[dict]:
    pdfs = [_with_bubble_score(m, slug) for m in (asset_metas if asset_metas is not None else assets.list_assets())
            if slug in m.get("idea_bubbles", [])]
    pdfs.sort(key=_paper_sort_key)
    return pdfs


def add_pdf_to_bubble(slug: str, pdf_id: str) -> dict:
    """Make an existing PDF a member of this bubble by tagging it with the bubble's name.

    Membership is derived from a PDF's ``idea_bubbles`` (slugs of its tags), so we append a tag
    that slugifies back to this bubble's slug (``tag_for_slug``) and let ``assets.update_asset``
    re-sync the slug list. We deliberately do NOT use the display name: if the bubble was renamed,
    its name slugifies to a different slug and the PDF would join a phantom bubble. Idempotent: a
    no-op if the PDF is already a member.
    """
    meta = assets.load_meta(pdf_id)
    if slug in meta.get("idea_bubbles", []):
        scores = assets.bubble_scores(meta)
        if slug not in (meta.get("bubble_scores") or {}):
            meta["bubble_scores"] = scores
            assets.save_meta(pdf_id, meta)
        return _with_bubble_score(meta, slug)
    tags = list(meta.get("tags", []))
    tags.append(tag_for_slug(slug))
    updated = assets.update_asset(pdf_id, tags=tags)
    scores = assets.bubble_scores(updated)
    scores[slug] = 5
    updated["bubble_scores"] = scores
    assets.save_meta(pdf_id, updated)
    touch_bubble(slug)
    write_citation_file(slug)
    return _with_bubble_score(updated, slug)


def remove_pdf_from_bubble(slug: str, pdf_id: str) -> dict:
    """Drop this bubble's tag from a PDF so it leaves the bubble (stays in Assets / other
    bubbles). ``update_asset`` re-syncs ``idea_bubbles`` from the trimmed tag list. Idempotent."""
    meta = assets.load_meta(pdf_id)
    if slug not in meta.get("idea_bubbles", []):
        return meta
    tags = [t for t in meta.get("tags", []) if assets.slug_of(t) != slug]
    updated = assets.update_asset(pdf_id, tags=tags)
    scores = assets.bubble_scores(updated)
    scores.pop(slug, None)
    updated["bubble_scores"] = scores
    assets.save_meta(pdf_id, updated)
    touch_bubble(slug)
    write_citation_file(slug)
    return updated


def set_pdf_bubble_score(slug: str, pdf_id: str, score: int) -> dict:
    """Set a PDF's relevance score inside a bubble, preserving membership."""
    if score < 1 or score > 5:
        raise ValueError("Relevance score must be an integer from 1 to 5.")
    meta = assets.load_meta(pdf_id)
    if slug not in meta.get("idea_bubbles", []):
        raise KeyError(f"Asset {pdf_id!r} is not attached to bubble {slug!r}.")
    scores = assets.bubble_scores(meta)
    scores[slug] = int(score)
    meta["bubble_scores"] = scores
    assets.save_meta(pdf_id, meta)
    touch_bubble(slug)
    return _with_bubble_score(meta, slug)


def memberships_for_asset(pdf_id: str) -> list[dict]:
    """Return approved bubble memberships for one asset, including relevance."""
    meta = assets.load_meta(pdf_id)
    scores = assets.bubble_scores(meta)
    reg = load_registry()
    pdf_names = _pdf_slug_names()
    out = []
    for slug in meta.get("idea_bubbles", []) or []:
        out.append({
            "slug": slug,
            "name": slug_to_name(slug, reg=reg, pdf_names=pdf_names),
            "tag": tag_for_slug(slug, reg=reg, pdf_names=pdf_names),
            "score": scores.get(slug, 5),
            "approved": bool(reg.get(slug, {}).get("approved")),
        })
    out.sort(key=lambda x: (-int(x.get("score", 5)), x.get("name", "").lower(), x.get("slug", "")))
    return out


def all_bubbles() -> list[dict]:
    """Union of registry bubbles and PDF-derived bubbles."""
    reg = load_registry()
    asset_metas = assets.list_assets()
    pdf_names = _pdf_slug_names(asset_metas)
    counts: dict[str, int] = {}
    for m in asset_metas:
        for slug in m.get("idea_bubbles", []):
            counts[slug] = counts.get(slug, 0) + 1

    slugs = set(reg) | set(pdf_names)
    out = []
    for slug in sorted(slugs):
        entry = reg.get(slug, {})
        name = entry.get("name") or pdf_names.get(slug, slug)
        last_edited_at = entry.get("last_edited_at") or entry.get("created_at") or ""
        out.append({
            "slug": slug,
            "name": name,
            "tag": tag_for_slug(slug, reg=reg, pdf_names=pdf_names),
            "approved": bool(entry.get("approved", False)),
            "in_registry": slug in reg,
            "pdf_count": counts.get(slug, 0),
            "page_count": _page_count(slug),
            "instructions": entry.get("instructions", ""),
            "last_edited_at": last_edited_at,
        })
    out.sort(key=lambda b: b.get("last_edited_at") or "", reverse=True)
    return out


def bubble_detail(slug: str) -> dict:
    reg = load_registry()
    entry = reg.get(slug, {})
    asset_metas = assets.list_assets()
    pdf_names = _pdf_slug_names(asset_metas)
    pdfs = pdfs_for_bubble(slug, asset_metas=asset_metas)
    approved = bool(entry.get("approved", False))
    pages, home, content = [], "", ""
    if approved:
        ensure_pages(slug)
        pages = list_pages(slug)
        home = manifest(slug).get("home", pages[0]["page_slug"] if pages else "")
        content = get_page(slug, home) if home else ""
    return {
        "slug": slug,
        "name": entry.get("name") or slug_to_name(slug, reg=reg, pdf_names=pdf_names),
        "tag": tag_for_slug(slug, reg=reg, pdf_names=pdf_names),
        "approved": approved,
        "in_registry": slug in reg,
        "instructions": entry.get("instructions", ""),
        "last_edited_at": entry.get("last_edited_at") or entry.get("created_at") or "",
        "pdf_count": len(pdfs),
        "page_count": _page_count(slug),
        "assets": pdfs,
        "images": list_bubble_images(slug),
        "pages": pages,
        "home": home,
        "page": home,
        "content": content,
        "share_active": bool(entry.get("share_active", False)),
        "share_token": entry.get("share_token", ""),
    }


# --------------------------------------------------------------------------- #
# Public sharing — an unlisted, read-only link per bubble
# --------------------------------------------------------------------------- #
def set_share_active(slug: str, active: bool) -> dict:
    """Toggle a bubble's public share. Mints a permanent token on first activation.

    Returns ``{"share_active", "share_token"}``. The token is stable: turning sharing off then
    back on restores the same link. Auto-suggested bubbles are materialized into the registry so
    the share state has somewhere to live.
    """
    reg = load_registry()
    entry = reg.get(slug)
    if entry is None:
        entry = {"name": slug_to_name(slug), "approved": True, "instructions": "",
                 "created_at": _now_iso()}
    token = entry.get("share_token") or secrets.token_urlsafe(16)
    entry["share_token"] = token
    entry["share_active"] = bool(active)
    entry["last_edited_at"] = entry.get("last_edited_at") or entry.get("created_at") or _now_iso()
    reg[slug] = entry
    save_registry(reg)
    return {"share_active": bool(active), "share_token": token}


# --------------------------------------------------------------------------- #
# Pages — a per-bubble mini-wiki of markdown files (v2)
# --------------------------------------------------------------------------- #
def manifest(slug: str) -> dict:
    p = paths.bubble_manifest_path(slug)
    if not p.exists():
        return {"home": "", "pages": []}
    data = yaml.safe_load(p.read_text()) or {}
    data.setdefault("home", "")
    data.setdefault("pages", [])
    return data


def _save_manifest(slug: str, data: dict) -> None:
    _atomic_write(paths.bubble_manifest_path(slug),
                  yaml.safe_dump(data, sort_keys=False, allow_unicode=True))


def _page_count(slug: str) -> int:
    return len(manifest(slug).get("pages", []))


def _unique_page_slug(slug: str, title: str) -> str:
    base = slugify(title) or "page"
    existing = {p["page_slug"] for p in manifest(slug).get("pages", [])}
    if base not in existing:
        return base
    i = 2
    while f"{base}-{i}" in existing:
        i += 1
    return f"{base}-{i}"


def ensure_pages(slug: str) -> None:
    """Idempotent: migrate a legacy report.md into pages/, else seed a default Overview page."""
    if paths.bubble_manifest_path(slug).exists():
        return
    paths.bubble_pages_dir(slug).mkdir(parents=True, exist_ok=True)
    legacy = paths.bubble_report_path(slug)
    if legacy.exists():
        _atomic_write(paths.bubble_page_path(slug, "overview"), legacy.read_text())
        try:
            legacy.unlink()
        except OSError:
            pass
    else:
        name = slug_to_name(slug)
        _atomic_write(paths.bubble_page_path(slug, "overview"), f"# {name}\n\n")
    _save_manifest(slug, {"home": "overview", "pages": [{"page_slug": "overview",
                                                         "title": "Overview"}]})


def list_pages(slug: str) -> list[dict]:
    ensure_pages(slug)
    return manifest(slug).get("pages", [])


def get_page(slug: str, page_slug: str) -> str:
    p = paths.bubble_page_path(slug, page_slug)
    return p.read_text() if p.exists() else ""


_WIKILINK_RE = re.compile(r"\[\[([^\]]+)\]\]")


def normalize_wikilinks(slug: str, content: str) -> str:
    """Rewrite ``[[X]]`` link targets to real page slugs.

    Models (especially small local ones) guess link targets — they invent path-like
    forms (``[[Key Papers/Some Title]]``) or write the human title (``[[Some Title]]``)
    instead of the slug the server assigned. This resolves each target against the
    bubble's page list: a leading ``prefix/`` is stripped, then the target is matched
    by slug first, then by title (case-insensitive). Unresolved targets are left as-is
    (prefix-stripped) so the user's literal text survives. Idempotent.
    """
    try:
        pages = manifest(slug).get("pages", [])
    except Exception:  # noqa: BLE001 — never let link cleanup break a save
        return content
    slugs = {p["page_slug"] for p in pages}
    by_title = {p["title"].strip().lower(): p["page_slug"] for p in pages}

    def repl(m: "re.Match") -> str:
        raw = m.group(1).strip()
        if "|" in raw:
            target, label = raw.split("|", 1)
            target = target.strip()
            label = label.strip()
        else:
            target = raw
            label = None
        if "/" in target:                      # drop invented "Section/Title" prefixes
            target = target.split("/")[-1].strip()
        if target in slugs:
            normalized = target
        else:
            hit = by_title.get(target.lower())
            normalized = hit if hit else target
        return f"[[{normalized}|{label}]]" if label is not None else f"[[{normalized}]]"

    return _WIKILINK_RE.sub(repl, content)


class PageConflict(Exception):
    """Page changed on disk since the editor loaded it.

    Raised by :func:`save_page` when an optimistic ``base_mtime`` no longer matches the
    file's current mtime — i.e. something edited the page out-of-band (e.g. a dev-mode
    direct file edit) since the content the caller is about to write was loaded. The
    caller (the autosave path) surfaces this as an "unsynced" conflict the user resolves
    by hand, rather than silently clobbering the external edit.
    """

    def __init__(self, disk_mtime: float):
        super().__init__("page changed on disk")
        self.disk_mtime = disk_mtime


def save_page(slug: str, page_slug: str, content: str,
              base_mtime: "float | None" = None) -> float:
    """Write a page atomically (after wikilink normalization); return its new mtime.

    If ``base_mtime`` is given, it's an optimistic-concurrency guard: when the file's
    current mtime differs (an external edit happened since it was loaded), raise
    :class:`PageConflict` instead of overwriting. ``None`` (the default) skips the check
    and always writes — preserving every existing caller.
    """
    path = paths.bubble_page_path(slug, page_slug)
    if base_mtime is not None and path.exists():
        disk_mtime = path.stat().st_mtime
        if abs(disk_mtime - base_mtime) > 1e-6:
            raise PageConflict(disk_mtime)
    _atomic_write(path, normalize_wikilinks(slug, content))
    touch_bubble(slug)
    return path.stat().st_mtime


def create_page(slug: str, title: str) -> str:
    ensure_pages(slug)
    page_slug = _unique_page_slug(slug, title)
    _atomic_write(paths.bubble_page_path(slug, page_slug), f"# {title.strip()}\n\n")
    data = manifest(slug)
    data["pages"].append({"page_slug": page_slug, "title": title.strip() or page_slug})
    _save_manifest(slug, data)
    touch_bubble(slug)
    return page_slug


def register_page(slug: str, page_slug: str, content: str) -> None:
    """Register a Scientist-created page whose filename is already its stable slug.

    Browser-created pages choose their slug from a human title.  Scientist instead starts with
    ``pages/<page_slug>.md``, so this keeps that filename stable while using the same manifest
    and link-normalization invariants as every other page creation path.
    """
    if not page_slug or slugify(page_slug) != page_slug:
        raise ValueError("Invalid page slug.")
    ensure_pages(slug)
    data = manifest(slug)
    if any(p["page_slug"] == page_slug for p in data.get("pages", [])):
        raise ValueError("Page already exists.")
    _atomic_write(paths.bubble_page_path(slug, page_slug), normalize_wikilinks(slug, content))
    data.setdefault("pages", []).append({"page_slug": page_slug,
                                          "title": page_slug.replace("-", " ")})
    _save_manifest(slug, data)
    touch_bubble(slug)


def rename_page(slug: str, page_slug: str, title: str) -> None:
    data = manifest(slug)
    old_title = ""
    for p in data["pages"]:
        if p["page_slug"] == page_slug:
            old_title = p["title"]
            p["title"] = title.strip() or page_slug
    _save_manifest(slug, data)
    touch_bubble(slug)
    new_title = title.strip() or page_slug
    if old_title and old_title.lower() != new_title.lower():
        _rewrite_title_links(slug, old_title, page_slug)


def set_page_hidden(slug: str, page_slug: str, hidden: bool) -> None:
    data = manifest(slug)
    for p in data["pages"]:
        if p["page_slug"] == page_slug:
            p["hidden"] = bool(hidden)
            _save_manifest(slug, data)
            touch_bubble(slug)
            return
    raise KeyError(page_slug)


def reorder_pages(slug: str, page_slugs: list[str]) -> None:
    data = manifest(slug)
    pages = data.get("pages", [])
    current = [p["page_slug"] for p in pages]
    if set(page_slugs) != set(current) or len(page_slugs) != len(current):
        raise ValueError("Page order must contain each existing page exactly once.")
    by_slug = {p["page_slug"]: p for p in pages}
    data["pages"] = [by_slug[s] for s in page_slugs]
    _save_manifest(slug, data)
    touch_bubble(slug)


def _rewrite_title_links(slug: str, old_title: str, page_slug: str) -> None:
    """Replace [[Old Title]] with [[page_slug]] across all pages after a title rename."""
    old_lower = old_title.lower()

    def repl(m: "re.Match") -> str:
        raw = m.group(1).strip()
        if "|" in raw:
            target, label = raw.split("|", 1)
            if target.strip().lower() == old_lower:
                return f"[[{page_slug}|{label.strip()}]]"
            return m.group(0)
        if raw.lower() == old_lower:
            return f"[[{page_slug}]]"
        return m.group(0)

    for p in manifest(slug).get("pages", []):
        path = paths.bubble_page_path(slug, p["page_slug"])
        try:
            content = path.read_text()
            new_content = _WIKILINK_RE.sub(repl, content)
            if new_content != content:
                _atomic_write(path, new_content)
        except Exception:  # noqa: BLE001
            pass


def delete_page(slug: str, page_slug: str) -> bool:
    data = manifest(slug)
    if page_slug == data.get("home"):
        raise ValueError("Cannot delete the home page.")
    before = len(data["pages"])
    data["pages"] = [p for p in data["pages"] if p["page_slug"] != page_slug]
    if len(data["pages"]) == before:
        return False
    _save_manifest(slug, data)
    try:
        paths.bubble_page_path(slug, page_slug).unlink()
    except OSError:
        pass
    touch_bubble(slug)
    return True


# --------------------------------------------------------------------------- #
# Figures / images
# --------------------------------------------------------------------------- #
_GIF_LOOP_EXTENSION = b"!\xff\x0bNETSCAPE2.0\x03\x01\x00\x00\x00"


def ensure_looping_gif(data: bytes) -> bytes:
    """Add GIF's standard infinite-loop extension when an animation lacks one.

    Browsers honour an animated GIF's loop metadata; replacing an ``img`` source can restart
    it, but cannot turn a single-play GIF into a repeating animation.  This lossless byte-level
    insertion happens before the GIF's first block, after its optional global colour table.
    """
    if not (data.startswith((b"GIF87a", b"GIF89a")) and len(data) >= 13):
        return data
    if b"NETSCAPE2.0" in data or b"ANIMEXTS1.0" in data:
        return data
    packed = data[10]
    global_table_size = 3 * (1 << ((packed & 0x07) + 1)) if packed & 0x80 else 0
    offset = 13 + global_table_size
    if offset > len(data):
        return data
    return data[:offset] + _GIF_LOOP_EXTENSION + data[offset:]


def save_bubble_image(slug: str, filename: str, data: bytes) -> str:
    """Save an uploaded image under assets/ with a safe unique name; return its URL."""
    adir = paths.bubble_assets_dir(slug)
    adir.mkdir(parents=True, exist_ok=True)
    stem = slugify(Path(filename).stem) or "image"
    ext = (Path(filename).suffix or ".png").lower()
    name = f"{stem}{ext}"
    i = 2
    while (adir / name).exists():
        name = f"{stem}-{i}{ext}"
        i += 1
    if ext == ".gif":
        data = ensure_looping_gif(data)
    (adir / name).write_bytes(data)
    return f"/api/bubbles/{slug}/assets/{name}"


def list_bubble_images(slug: str) -> list[str]:
    adir = paths.bubble_assets_dir(slug)
    if not adir.exists():
        return []
    return sorted(f"/api/bubbles/{slug}/assets/{p.name}" for p in adir.iterdir() if p.is_file())


# --------------------------------------------------------------------------- #
# Chat session persistence
# --------------------------------------------------------------------------- #
def _chats_dir(slug: str) -> Path:
    return paths.bubble_chats_dir(slug)


def _session_path(slug: str, session_id: str) -> Path:
    safe = slugify(session_id, separator="-") or session_id.replace("/", "-")
    return _chats_dir(slug) / f"{safe}.json"


def list_chat_sessions(slug: str) -> list[dict]:
    d = _chats_dir(slug)
    if not d.exists():
        return []
    out = []
    for p in sorted(d.glob("*.json"), reverse=True):
        try:
            data = _json.loads(p.read_text())
            msgs = data.get("messages", [])
            preview = next((m["content"][:80] for m in msgs if m.get("role") == "user"), "")
            out.append({"id": data.get("id", p.stem), "title": data.get("title", "Chat"),
                        "created_at": data.get("created_at", ""), "preview": preview})
        except Exception:  # noqa: BLE001
            continue
    return out


def get_chat_session(slug: str, session_id: str) -> dict | None:
    p = _session_path(slug, session_id)
    if not p.exists():
        return None
    try:
        return _json.loads(p.read_text())
    except Exception:  # noqa: BLE001
        return None


def save_chat_session(slug: str, session_id: str, title: str, messages: list[dict]) -> None:
    d = _chats_dir(slug)
    d.mkdir(parents=True, exist_ok=True)
    path = _session_path(slug, session_id)
    data = {"id": session_id, "title": title,
            "created_at": _now_iso(), "messages": messages}
    _atomic_write(path, _json.dumps(data, ensure_ascii=False, indent=2))


def delete_chat_session(slug: str, session_id: str) -> bool:
    p = _session_path(slug, session_id)
    if not p.exists():
        return False
    p.unlink()
    return True
